version: '3'

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped

    environment:
      - TZ="America/New_York"

    volumes:
      - netdata:/etc/netdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

    ports:
      - 19999:19999

    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined

    healthcheck:
      test: curl --fail -s http://localhost:19999/ || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
    netdata:
