version: '3'

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    restart: unless-stopped

    volumes:
      - ${appdata}/heimdall:/config
      - /etc/localtime:/etc/localtime:ro

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York

    ports:
      - 9000:80

    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
